### PR TITLE
Title to QR Code

### PR DESCRIPTION
**Pull request by alexandregz**
We can put title to QR Code, looks better into Google Authenticator Android App (suggestion by Peter Tobias)

### CODE REVIEW

**Comment by PHPGangsta** [comment]
Hi Alexandre,

please fix 2 small things, then I'm happy to merge your pull request:

$title=null
should be
$title = null

Correct the indenting of your new "if" line, and please use {} around the statement.

Then the code style is correct and I can merge your change.

Thanks!
Michael

**Comment by alexandregz** [comment]
done (also updated branch)

**Comment by PHPGangsta** [comment]
Thanks, merged!

**Comment by alexandregz** [comment]
You're welcome!

**Pull request merged**
