### PR TITLE
array_rand does not use secure random

### PR DESCRIPTION
**Pull request by Sc00bz**

### CODE REVIEW

**Comment by PHPGangsta** [comment]
Hi Steve,

One test is failing, because it tries to generate a secret with length 0, and mcrypt_create_iv() does not allow that:
testCreateSecretLengthCanBeSpecified()
See failed Travis build.

If you fix the test (it should start from 1 instead of 0), all tests should pass.

**Comment by RobThree** [comment]
A secret length of 0 makes no sense anyway; the (very) minimum value should be (around) 80 bits and I would throw an exception on anything less. I also find it pretty arbitrary to test for values 0...100 (why 100 and not... 97? 109? 2091? 729183019?). It would make more sense to test for specifice ("edge") cases and commonly used cases:

* Make sure you throw an exception on anything less than, say, 80 bits (80 bits is Google's recommended minimum (if I recall correctly))
* Test for common values (like 128, 160, 256, ...)
* Test for upper bounds that can/will cause exceptions in underlying implementations or bounds that you set yourself (like, say, 4096) to keep things sane.

**Comment by jippi** [comment]
:+1:

**Comment by Sc00bz** [comment]
Umm I guess I can't just throw an exception because that causes the Travis CI build to failed. Will changing it to die(...) make it fail too?

**Comment by RobThree** [comment]
You could `die` or return an error code of some sort or whatever indicates that something is wrong. But having said that: exceptions can, ofcourse, also be unit-tested. In fact: you can indicate that you **expect** some method to throw an exception (or even more specific: you expect it to throw Exception of type X); the unit-test will PASS on that exception and FAIL if the exception **isn't** thrown. So throwing an exception doesn't automatically imply you can't unittest that code.

You can see [here](https://github.com/RobThree/TwoFactorAuth/blob/master/tests/TwoFactorAuthTest.php) for example (noted by the `@expectedException`) how to unittest code that is *supposed* to throw an exception.

**Comment by Conver** [comment]
+1

**Pull request merged**
